# GNINA Docker Image
# Uses pre-built image from Docker Hub
FROM gnina/gnina:latest

LABEL maintainer="BioDockify"
LABEL description="GNINA - Deep Learning Molecular Docking with CNN Scoring"

WORKDIR /data

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV RECEPTOR_FILE=/data/receptor.pdbqt
ENV LIGAND_FILE=/data/ligand.pdbqt

ENTRYPOINT ["/entrypoint.sh"]
